<?php

return [
    'super_admin' => [
        'dashboard.read',
        'merchants.read',
        'merchants.create',
        'merchants.status.change',
        'merchants.status.enable',
        'destination_wallets.read',
        'destination_wallets.write',
        'merchant_users.read',
        'merchant_users.create',
        'merchant_users.roles.write',
        'merchant_users.status.change',
        'merchant_users.status.enable',
        'invoices.read',
        'invoices.refresh',
        'webhook_deliveries.read',
        'webhook_deliveries.retry',
        'merchant_api_keys.read',
        'merchant_api_keys.revoke',
    ],
    'support' => [
        'dashboard.read',
        'merchants.read',
        'merchants.status.change',
        'destination_wallets.read',
        'merchant_users.read',
        'merchant_users.status.change',
        'invoices.read',
        'invoices.refresh',
        'webhook_deliveries.read',
        'webhook_deliveries.retry',
        'merchant_api_keys.read',
        'merchant_api_keys.revoke',
    ],
    'analyst' => [
        'dashboard.read',
        'merchants.read',
        'destination_wallets.read',
        'merchant_users.read',
        'invoices.read',
        'webhook_deliveries.read',
        'merchant_api_keys.read',
    ],
];
